### ISSUE TITLE
column "to_address" of relation "transactions" does not exist

### ISSUE THREAD

**Issue by Jangam** [tronscan/tronscan-api#46]
(FULL NODE BLOCK,3008)
[error] application - Query Exception
org.postgresql.util.PSQLException: ERROR: column "to_address" of relation "transactions" does not exist
  Position: 87
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.$anonfun$run$11(JdbcActionComponent.scala:510)
(FULL NODE BLOCK,3009)
(FULL NODE BLOCK,3010)

**Comment by Jangam** [comment]
I recreated the database with fresh schema script and problem solved.
Ty
